# Generated by Django 2.1.7 on 2019-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('poem_body', models.CharField(max_length=1000)),
                ('dynasty', models.CharField(max_length=100)),
                ('tac', models.CharField(max_length=1000)),
                ('appreciation', models.CharField(max_length=1000)),
                ('background', models.CharField(max_length=1000)),
                ('self_intro', models.CharField(max_length=1000)),
            ],
        ),
    ]
